### ISSUE TITLE
Format of zone file?

### ISSUE THREAD

**Issue by bkrugerp99** [yahoo/SubdomainSleuth#3]
What format do you want the zone to be in?  bind? cli53 output? djbdns? powerdns?

## Expected Behavior
Docs should be a little more verbose of format to be used.

## Current Behavior
Docs don't tell us format for the zone file?

## Possible Solution
Fixing the docs.

## Steps to Reproduce (for bugs)

1. Read the docs.
2. Search for any clue of zone format (hint: if I search for bind as I'm making a guess as the format, it doesn't turn up)

## Context
I'm wishing to use https://github.com/barnybug/cli53 to be able to parse aws zones.
You can get a bind-compatible output by using "export".

**Comment by paulf69487623** [comment]
Hey Brian,

Yeah, we could clarify that a little more.  This version currently only supports reading Bind / RFC 1035 style zone files.  If you're up for it, you can open a PR with the clarification.

Is there a generally recognized format for AWS R53 zone files?  It would definitely be possible to add support for parsing that.  One of our internal versions had support for loading records exported to an internal JSON format.  The implementation of that format wasn't very elegant, but I've got an idea of how it could be done more nicely.

Thanks,

Paul
