### ISSUE TITLE
Edge case: output with zero errors is "null" instead of "[]"

### ISSUE THREAD

**Issue by jakajancar** [yahoo/SubdomainSleuth#4]
It's unclear from the docs what the output should be, but with zero errors it's "null" instead of "[]", as it would make sense to me given that otherwise it's a pretty-printed array.

**Comment by paulf69487623** [comment]
I just confirmed this behavior.  I did a little checking, and this is the default behavior if you have an empty slice.  I found https://apoorvam.github.io/blog/2017/golang-json-marshal-slice-as-empty-array-not-null/ that demonstrates this behavior.

If you initialize the results slice with an actual empty array as described on that page, you get the expected `[]` output.

```
var results Results = make([]Result, 0)
```

I'll try to get this integrated sometime in the next week, or you could open a PR if you're interested.
